### ISSUE TITLE
Sub emotes?

### ISSUE THREAD

**Issue by azizLIGHT** [Phineas05/TwitchEmotes#2]
Could you please make it so we can see sub emotes of specific streamers of our choosing on any website. Maybe with a choice to pick tier 1, tier 2, or tier 3 if you can.
Thanks

**Comment by Phineas05** [comment]
Added with commit https://github.com/Phineas05/TwitchEmotes/commit/e37336e47e275a352b771e7321c4b7355d600b60. Add channels from the settings page.
